---
# tasks file for docker-registry
- name: login
  docker_login:
    email: tayeb.ahmed@esprit.tn
    username: tybahmed
    password: Cloudcomputing
    reauthorize: yes
- name: docker push
  docker_image:
    name: devops:latest
    repository: tybahmed/projetcl
    push: yes
    source: local    
