---
# tasks file for docker-registry
- name: login
  docker_login:
    email: "tayeb.ahmed@esprit.tn"
    username: "tybahmed"
    password: "Cloudcomputing"
- name: docker push
  docker_image:
    name: devops:latest
    push: yes
    source: local    
